# Site settings
name: Glitched.
title: Glitched.
description: Modern, sharp template powered by Jekyll
url: https://exonglish.github.io
baseurl: ""

# Build settings
markdown: kramdown
permalink: /posts/:title/
collections:
  posts:
    output: true
    permalink: /posts/:title/

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - footer-styles.html

# GitHub Pages safe mode (no custom plugins)
safe: true
plugins: []
